# Generated by Django 5.0.2 on 2024-02-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.IntegerField()),
                ('courseNumber', models.IntegerField()),
                ('courseLetters', models.CharField(max_length=3)),
                ('professor', models.CharField(max_length=45)),
                ('homeworkDiff', models.IntegerField()),
                ('lectureDiff', models.IntegerField()),
                ('workLoad', models.IntegerField()),
                ('examDiff', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='courseTaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.IntegerField()),
                ('userName', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=45)),
                ('userName', models.CharField(max_length=75)),
            ],
        ),
    ]
