# Generated by Django 5.0.2 on 2024-04-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='numOfRatings',
            field=models.IntegerField(default=0),
        ),
    ]
