# Generated by Django 5.0.2 on 2024-04-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_courses_numofratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='examDiff',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='homeworkDiff',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='lectureDiff',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='courses',
            name='workLoad',
            field=models.FloatField(),
        ),
    ]
