# Generated by Django 5.0.2 on 2024-04-02 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_courses_coursename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baseuser',
            fields=[
                ('mycustomuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('main.mycustomuser',),
        ),
        migrations.CreateModel(
            name='Paiduser',
            fields=[
                ('mycustomuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('main.mycustomuser',),
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='type',
            field=models.CharField(choices=[('PAIDUSER', 'Paiduser'), ('BASEUSER', 'Baseuser')], default='BASEUSER', max_length=50, verbose_name='Types'),
        ),
    ]
